-- Backup de políticas RLS de Supabase (kids_game) -- generado 2026-07-30
-- Nota: estas políticas ya EXISTEN en la base de datos actual. Este archivo es
-- solo de referencia/restauración; no se debe ejecutar contra una base que ya
-- las tiene (dará error de "policy already exists").

CREATE POLICY "no select" ON public.analytics_events AS PERMISSIVE FOR SELECT TO public USING (false);
CREATE POLICY "user inserts own events" ON public.analytics_events AS PERMISSIVE FOR INSERT TO public WITH CHECK (((auth.uid() = user_id) OR (user_id IS NULL)));
CREATE POLICY "public read badge_definitions" ON public.badge_definitions AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "Lectura pública de diálogos" ON public.blink_dialogues AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "no direct insert equipped" ON public.character_equipped AS PERMISSIVE FOR INSERT TO public WITH CHECK (false);
CREATE POLICY "no direct update equipped" ON public.character_equipped AS PERMISSIVE FOR UPDATE TO public USING (false);
CREATE POLICY "parent reads child equipped" ON public.character_equipped AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM parent_child WHERE ((parent_child.parent_id = auth.uid()) AND (parent_child.child_id = character_equipped.user_id)))));
CREATE POLICY "player reads own equipped" ON public.character_equipped AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = user_id));
CREATE POLICY "Papá ve personaje de hijos" ON public.characters AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM parent_child WHERE ((parent_child.parent_id = auth.uid()) AND (parent_child.child_id = characters.user_id)))));
CREATE POLICY "Personaje propio — actualizar" ON public.characters AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Personaje propio — crear" ON public.characters AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Personaje propio — leer" ON public.characters AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = user_id));
CREATE POLICY "child_goals — acceso propio" ON public.child_goals AS PERMISSIVE FOR ALL TO public USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "public read cosmetics catalog" ON public.cosmetic_definitions AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "no select crash" ON public.crash_reports AS PERMISSIVE FOR SELECT TO public USING (false);
CREATE POLICY "user inserts own crash" ON public.crash_reports AS PERMISSIVE FOR INSERT TO public WITH CHECK (((auth.uid() = user_id) OR (user_id IS NULL)));
CREATE POLICY "Inventario propio — insertar" ON public.inventory AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Inventario propio — leer" ON public.inventory AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = user_id));
CREATE POLICY "invite_codes — padre lee los suyos" ON public.invite_codes AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = parent_id));
CREATE POLICY "Catálogo activo — lectura pública" ON public.item_catalog AS PERMISSIVE FOR SELECT TO public USING ((is_active = true));
CREATE POLICY "Lectura pública de definiciones de ítems" ON public.item_definitions AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "Trabajos propios — leer/escribir" ON public.job_completions AS PERMISSIVE FOR ALL TO public USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Trabajos activos — lectura pública" ON public.jobs AS PERMISSIVE FOR SELECT TO public USING ((is_active = true));
CREATE POLICY child_reads_own_requests ON public.link_requests AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = child_id));
CREATE POLICY child_updates_status ON public.link_requests AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = child_id));
CREATE POLICY parent_inserts_requests ON public.link_requests AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = parent_id));
CREATE POLICY parent_reads_own_requests ON public.link_requests AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = parent_id));
CREATE POLICY "Mercado — leer todos los listados activos" ON public.market_listings AS PERMISSIVE FOR SELECT TO public USING (((status = 'active'::listing_status) OR (seller_id = auth.uid()) OR (buyer_id = auth.uid())));
CREATE POLICY "Mercado — publicar listado" ON public.market_listings AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = seller_id));
CREATE POLICY "mission_claims — propio" ON public.mission_claims AS PERMISSIVE FOR ALL TO public USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Misiones propias — leer/escribir" ON public.mission_participants AS PERMISSIVE FOR ALL TO public USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "mission_progress — propio" ON public.mission_progress AS PERMISSIVE FOR ALL TO public USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Misiones activas — lectura pública" ON public.missions AS PERMISSIVE FOR SELECT TO public USING ((status = 'active'::mission_status));
CREATE POLICY anyone_inserts_notifications ON public.notifications AS PERMISSIVE FOR INSERT TO public WITH CHECK (true);
CREATE POLICY user_reads_own_notifications ON public.notifications AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = user_id));
CREATE POLICY user_updates_own_notifications ON public.notifications AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = user_id));
CREATE POLICY "parent_child — leer propias" ON public.parent_child AS PERMISSIVE FOR SELECT TO public USING (((auth.uid() = parent_id) OR (auth.uid() = child_id)));
CREATE POLICY child_reads_own_missions ON public.parent_missions AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = child_id));
CREATE POLICY parent_reads_own_missions ON public.parent_missions AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = parent_id));
CREATE POLICY parent_updates_pending_missions ON public.parent_missions AS PERMISSIVE FOR UPDATE TO public USING (((auth.uid() = parent_id) AND (status = 'pending'::text)));
CREATE POLICY "Respuestas propias — leer/escribir" ON public.player_answers AS PERMISSIVE FOR ALL TO public USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "no direct insert" ON public.player_badges AS PERMISSIVE FOR INSERT TO public WITH CHECK (false);
CREATE POLICY "parent reads child badges" ON public.player_badges AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM parent_child WHERE ((parent_child.parent_id = auth.uid()) AND (parent_child.child_id = player_badges.user_id)))));
CREATE POLICY "player reads own badges" ON public.player_badges AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = user_id));
CREATE POLICY "no direct insert cosmetics" ON public.player_cosmetics AS PERMISSIVE FOR INSERT TO public WITH CHECK (false);
CREATE POLICY "parent reads child cosmetics" ON public.player_cosmetics AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM parent_child WHERE ((parent_child.parent_id = auth.uid()) AND (parent_child.child_id = player_cosmetics.user_id)))));
CREATE POLICY "player reads own cosmetics" ON public.player_cosmetics AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = user_id));
CREATE POLICY "player_items — propio" ON public.player_items AS PERMISSIVE FOR ALL TO public USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "player_market_listings — crear propio" ON public.player_market_listings AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = seller_id));
CREATE POLICY "player_market_listings — eliminar propio" ON public.player_market_listings AS PERMISSIVE FOR DELETE TO public USING ((auth.uid() = seller_id));
CREATE POLICY "player_market_listings — leer todos" ON public.player_market_listings AS PERMISSIVE FOR SELECT TO public USING (true);
CREATE POLICY "Buscar niños para vinculación" ON public.profiles AS PERMISSIVE FOR SELECT TO public USING (((auth.uid() IS NOT NULL) AND (role = 'child'::user_role)));
CREATE POLICY "Crear perfil propio" ON public.profiles AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = id));
CREATE POLICY "Hijo ve perfil de su padre" ON public.profiles AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM parent_child WHERE ((parent_child.child_id = auth.uid()) AND (parent_child.parent_id = profiles.id)))));
CREATE POLICY "Papá ve perfil de hijos" ON public.profiles AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM parent_child WHERE ((parent_child.parent_id = auth.uid()) AND (parent_child.child_id = profiles.id)))));
CREATE POLICY "Perfil propio — actualizar" ON public.profiles AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = id));
CREATE POLICY "Perfil propio — leer" ON public.profiles AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = id));
CREATE POLICY "Usuario actualiza su propio pin" ON public.profiles AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = id)) WITH CHECK ((auth.uid() = id));
CREATE POLICY "user inserts own push log" ON public.push_notification_log AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "user reads own push log" ON public.push_notification_log AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = user_id));
CREATE POLICY templates_read ON public.push_notification_templates AS PERMISSIVE FOR SELECT TO authenticated USING ((is_active = true));
CREATE POLICY "Preguntas activas — lectura pública" ON public.questions AS PERMISSIVE FOR SELECT TO public USING ((is_active = true));
CREATE POLICY "Compras propias — leer" ON public.real_purchases AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = user_id));
CREATE POLICY "Transacciones propias — leer" ON public.transactions AS PERMISSIVE FOR SELECT TO public USING (((auth.uid() = from_user_id) OR (auth.uid() = to_user_id)));
CREATE POLICY "Tutorial propio — leer/escribir" ON public.tutorial_progress AS PERMISSIVE FOR ALL TO public USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY child_own_streak ON public.user_streaks AS PERMISSIVE FOR ALL TO public USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()));
CREATE POLICY parent_reads_child_streak ON public.user_streaks AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM parent_child pc WHERE ((pc.parent_id = auth.uid()) AND (pc.child_id = user_streaks.user_id)))));
CREATE POLICY "Categorías propias — actualizar" ON public.wallet_categories AS PERMISSIVE FOR UPDATE TO public USING ((EXISTS ( SELECT 1 FROM wallets WHERE ((wallets.id = wallet_categories.wallet_id) AND (wallets.user_id = auth.uid())))));
CREATE POLICY "Categorías propias — insertar" ON public.wallet_categories AS PERMISSIVE FOR INSERT TO public WITH CHECK ((EXISTS ( SELECT 1 FROM wallets WHERE ((wallets.id = wallet_categories.wallet_id) AND (wallets.user_id = auth.uid())))));
CREATE POLICY "Categorías propias — leer" ON public.wallet_categories AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM wallets WHERE ((wallets.id = wallet_categories.wallet_id) AND (wallets.user_id = auth.uid())))));
CREATE POLICY "Cartera propia — actualizar" ON public.wallets AS PERMISSIVE FOR UPDATE TO public USING ((auth.uid() = user_id));
CREATE POLICY "Cartera propia — leer" ON public.wallets AS PERMISSIVE FOR SELECT TO public USING ((auth.uid() = user_id));
CREATE POLICY "Crear cartera propia" ON public.wallets AS PERMISSIVE FOR INSERT TO public WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Papá ve cartera de hijos" ON public.wallets AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM parent_child WHERE ((parent_child.parent_id = auth.uid()) AND (parent_child.child_id = wallets.user_id)))));
CREATE POLICY child_reads_own_salary ON public.weekly_salaries AS PERMISSIVE FOR SELECT TO public USING ((child_id = auth.uid()));
CREATE POLICY parent_manages_salary ON public.weekly_salaries AS PERMISSIVE FOR ALL TO public USING ((parent_id = auth.uid())) WITH CHECK ((parent_id = auth.uid()));
CREATE POLICY child_own_fuel ON public.world_fuel AS PERMISSIVE FOR ALL TO public USING ((user_id = auth.uid())) WITH CHECK ((user_id = auth.uid()));
CREATE POLICY parent_reads_child_fuel ON public.world_fuel AS PERMISSIVE FOR SELECT TO public USING ((EXISTS ( SELECT 1 FROM parent_child pc WHERE ((pc.parent_id = auth.uid()) AND (pc.child_id = world_fuel.user_id)))));
CREATE POLICY "Casitas activas — lectura pública" ON public.world_houses AS PERMISSIVE FOR SELECT TO public USING ((is_active = true));
CREATE POLICY "world_progress — lectura propia" ON public.world_progress AS PERMISSIVE FOR ALL TO public USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));
CREATE POLICY "Mundos activos — lectura pública" ON public.worlds AS PERMISSIVE FOR SELECT TO public USING ((is_active = true));
CREATE POLICY "worlds — lectura pública" ON public.worlds AS PERMISSIVE FOR SELECT TO public USING (true);
